apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  fsGroup:
    rule: RunAsAny
  allowedCapabilities:
    - NET_RAW
  requiredDropCapabilities:
    - NET_RAW
  privileged: false
  allowPrivilegeEscalation: false
  automountServiceAccountToken: false
  requiredDropCapabilities: None
  runAsUser:
    rule: RunAsAny
  hostPID: false
  hostIPC: false
  hostNetwork: false
  hostPorts:
  - min: 1
    max: 65536
